name: "publish"

on:
  push:
    branches:
      - master

jobs:
    release: 
        name: publish
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2.4.2
          - name: node
            uses: actions/setup-node@v3
            with:
              node-version: 16
              registry-url: https://registry.npmjs.org
          - run: npm i --ignore-scripts
          - run: npm run build --if-present
            name: Build
          - name: publish
            run: npm publish --access public
            working-directory: dist/mv-client-core
            env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_PACKAGE }}